### ISSUE TITLE
Fails to load Boosters on Unique Items

### ISSUE THREAD

**Issue by Dalarrus** [NovFR/DoS-2-Savegame-Editor#1]
Loading the current boosters on any given Unique item seems to just fail outright, showing an empty Booster page.

Also had the program outright crash the first time I tried to modify a unique, but am Unable to reproduce.

**Comment by NovFR** [comment]
Can you upload your savegame somewhere ?

**Comment by Dalarrus** [comment]
Was mainly just messing around with it in a fresh save, used the editing to make one of the free weapons you get at the start deal stupid damage, and used that to get Dallis' Hammer from beating her up at the first encounter.

[Save file](https://github.com/NovFR/DoS-2-Savegame-Editor/files/4013291/herp.zip)

**Comment by NovFR** [comment]
I checked your savegame to be sure, everything seems ok.

Boosters are empty in some unique because there are no booster defined for those items.

They have a booster page because there is a "generation" node in their structure. The editor considers such items as "generated" and therefore allows booster editing, even if the node contains no boosters.

I admit this can be confusing.

**Comment by DaytonTNeuburger** [comment]
'Failed to convert resource: An item with the same key has already been added.'

Unsure what this means. I have a few ideas, but still not sure.

**Comment by NovFR** [comment]
Can you give me more details ? Looks like a divine.exe (LSlib) error message.
