### ISSUE TITLE
Description of file format?

### ISSUE THREAD

**Issue by tedgkassen** [NovFR/DoS-2-Savegame-Editor#10]
Hey thanks for making this! I just wanted to ask a question. I might be bad at reading C but I was just trying to figure out the file format of an LSV to see if I could get a straight XML output. It looked to me like it was just an LF4 compression XML file. Am I missing something here? When I tried to decompress with the command line lf4 tool, I was getting errors saying the headers are unrecognized

**Comment by NovFR** [comment]
You can't use standard tools to decompress and convert the files.

LSV is an archive containing all the files.

LSF is the XML file you are looking for. But it is not just a compressed XML text file. It is a binary file.

Most of the conversion job is done using [LSlib](https://github.com/Norbyte/lslib) not by my application, I only convert meta.lsf to show savegame informations. Files_Misc.c and Files_LSV.c contain direct port of Norbyte's C# code. If you want to understand files format, you better look his code rather than mine ^^

**Comment by tedgkassen** [comment]
Gotcha, makes sense. Thank you!
