### ISSUE TITLE
Single-handed bonuses?

### ISSUE THREAD

**Issue by m33ts4k0z** [NovFR/DoS-2-Savegame-Editor#19]
Hello and thanks for this great tool. It works great.

I wonder how can I add abilities like single-handed+ ?

When the item has them, they get recognised by the editor but I can't seem to be able to add them later or increase the bonus.

Thanks in advance.

**Comment by NovFR** [comment]
Hello, is it a booster or a permanent bonus ?

Known boosters are defined in Datas\Boosters.txt. If a booster is not present in this file, you won't be able to add it using the editor. But, this can be easily fixed by adding the missing ability in the file.

Have you the complete name of the missing abilities ?

For the increase, it must be defined in the game. The best way to fine tune such abilities is to use permanent bonus.

**Comment by m33ts4k0z** [comment]
Hello,

I noticed that using another way, you are able to add/edit the single-handed bonus. You can add it by going to Permanent Bonuses instead for the Boosters tab. No big deal since you can remove it through the Boosters tab and add it again, modified, through the Permanent Bonuses tab.
