### ISSUE TITLE
Duplicating an existing item

### ISSUE THREAD

**Issue by jonndoe47pp** [NovFR/DoS-2-Savegame-Editor#32]
For non stackable items you can't increase the quantity. And as I asked before you author(s) of this edit can't create new items in the inventory as that info isn't publicly available... But out of curiosity, would it be possible to copy an item and over write an existing inventory item ? Of course you would warn the user that this would erase for good the previous item.... Would this be a kludge/workaround on not being able to do this (it all has to do with the death fog barrel in case you wanted to know).

**Comment by NovFR** [comment]
Replacing an existing item would be easier indeed as I won't have to deal with InventoryViews and other stuff, but the problem remains. Deeply modifing items may have side effects I don't know, because I have no idea on how the game create items and what data it needs to function properly.

And to be honest, adding a new item would be theorically less "dangerous" than completely replacing existing one.

With my actual knowledge, I'm affraid I can't make such modifications.

**Comment by NovFR** [comment]
If you really want to experiment:

1. Take an item you can easily duplicate ingame (such as potions)
2. Split the stack to create stacks of 1 item
3. Save

Load your savegame into GlEd.
1. Find the item you want to duplicate
2. Open item's tree
    1. Copy the value of **Flags**
    2. Copy the value of **CurrentTemplate**
    3. Copy the value of **CurrentTemplateType**
    4. Copy the value of **Stats**
3. For each item you want to replace:
    1. Open item's tree
    2. Replace all the above values
4. Save and try ingame

I can't guarantee it will work as I haven't tested yet, but it can be a solution of your problem.

**Comment by jonndoe47pp** [comment]
I'll try those suggestions, but for now I'll close the ticket. Thanks for the feedback.
